const SITE = 'https://wicolly.com.br'
export const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')
export const list=(items=[],cls='tag-list')=>`<ul class="${cls}">${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`
const jsonLd=(v)=>JSON.stringify(v).replaceAll('<','\\u003c')
const PT=[['/','Início'],['/projetos/','Projetos'],['/ia/','IA'],['/infraestrutura/','Infraestrutura'],['/sobre/','Sobre'],['/diario/','Diário'],['/contato/','Contato']]
const EN=[['/en/','Home'],['/en/projects/','Projects'],['/en/ai/','AI'],['/en/infrastructure/','Infrastructure'],['/en/about/','About'],['/en/journal/','Journal'],['/en/contact/','Contact']]
const pairs=new Map([['/','/en/'],['/projetos/','/en/projects/'],['/ia/','/en/ai/'],['/infraestrutura/','/en/infrastructure/'],['/sobre/','/en/about/'],['/diario/','/en/journal/'],['/novidades/','/en/journal/'],['/contato/','/en/contact/'],['/blacklight3d/','/en/blacklight3d/'],['/blacklight3d/projetos/','/en/blacklight3d/projects/'],['/blacklight3d/orcamento/','/en/blacklight3d/quote/']])
export function paired(path,target){if(target==='en'){if(pairs.has(path))return pairs.get(path);const m=path.match(/^\/projetos\/([^/]+)\/$/);return m?`/en/projects/${m[1]}/`:'/en/'}for(const [pt,en] of pairs)if(en===path)return pt;const m=path.match(/^\/en\/projects\/([^/]+)\/$/);return m?`/projetos/${m[1]}/`:'/'}
function nav(path,lang){const en=lang==='en';const links=(en?EN:PT).map(([href,label])=>{const current=href===(en?'/en/':'/')?path===href:path.startsWith(href)||(href==='/diario/'&&path==='/novidades/');return `<a href="${href}"${current?' aria-current="page"':''}>${label}</a>`}).join('');return `<a class="skip-link" href="#conteudo">${en?'Skip to content':'Pular para o conteúdo'}</a><header class="site-header"><div class="nav-shell"><a class="wordmark" href="${en?'/en/':'/'}"><span class="brand-mark">W</span><span><strong>Wícolly</strong><small>${en?'technology in construction':'tecnologia em construção'}</small></span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="site-menu" data-menu-toggle>Menu</button><nav id="site-menu" class="site-nav" aria-label="${en?'Main navigation':'Navegação principal'}" data-menu>${links}</nav><div class="nav-actions"><div class="lang-switch" aria-label="Language"><a href="${paired(path,'pt')}"${!en?' class="active"':''} aria-label="Português"><span class="flag flag-br"></span><span class="lang-code">PT</span></a><a href="${paired(path,'en')}"${en?' class="active"':''} aria-label="English"><span class="flag flag-us"></span><span class="lang-code">EN</span></a></div><button class="theme-button" type="button" aria-label="Alternar tema" aria-pressed="false" data-theme-toggle>◐</button></div></div></header>`}
function footer(profile,links,lang){const en=lang==='en';return `<footer class="site-footer"><div class="shell footer-grid"><div><a class="wordmark footer-wordmark" href="${en?'/en/':'/'}"><span class="brand-mark">W</span><span><strong>Wícolly</strong><small>${en?'technology in construction':'tecnologia em construção'}</small></span></a><p>${esc(en?'Software, AI systems, self-hosted infrastructure and physical fabrication.':profile.shortBio)}</p></div><div><h2>${en?'Explore':'Explorar'}</h2><a href="${en?'/en/projects/':'/projetos/'}">${en?'Projects':'Projetos'}</a><a href="${en?'/en/ai/':'/ia/'}">AI Lab</a><a href="${en?'/en/infrastructure/':'/infraestrutura/'}">${en?'Infrastructure':'Infraestrutura'}</a><a href="${en?'/en/journal/':'/diario/'}">${en?'Journal':'Diário'}</a></div><div><h2>${en?'Contact':'Contato'}</h2><a href="${esc(links.linkedin)}" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href="${esc(links.github)}" target="_blank" rel="noopener noreferrer">GitHub</a><a href="mailto:${esc(links.email)}">${esc(links.email)}</a></div></div><div class="shell footer-bottom"><span>© <span data-current-year>2026</span> ${esc(profile.name)}.</span><a href="/privacidade/">${en?'Privacy (PT)':'Privacidade'}</a></div></footer>`}
export function layout({profile,links,title,description,path,body,lang='pt',scene='wicolly',bodyClass='',schema=[]}){const en=lang==='en',langCode=en?'en':'pt-BR',canonical=`${SITE}${path}`,alt=paired(path,en?'pt':'en');const schemas=[{'@context':'https://schema.org','@type':'WebSite',name:'Wícolly',url:SITE,inLanguage:langCode},...schema];return `<!doctype html><html lang="${langCode}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="${en?'pt-BR':'en'}" href="${SITE}${alt}"><meta name="theme-color" content="#07090d" data-theme-color><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${SITE}/shared/og-card.svg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:image" content="${SITE}/shared/og-card.svg"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><script src="/shared/theme.js"></script><link rel="stylesheet" href="/shared/redesign.css?v=__BUILD_VERSION__"><link rel="stylesheet" href="/shared/v6/core.css?v=__BUILD_VERSION__"><link rel="stylesheet" href="/shared/v6/components.css?v=__BUILD_VERSION__"><link rel="stylesheet" href="/shared/v6/blacklight.css?v=__BUILD_VERSION__">${schemas.map(x=>`<script type="application/ld+json">${jsonLd(x)}</script>`).join('')}</head><body class="${esc(bodyClass)}" data-scene-mode="${scene}" data-lang="${lang}">${nav(path,lang)}<canvas id="infinite-scene" class="scene-canvas" aria-hidden="true"></canvas><div class="scene-vignette" aria-hidden="true"></div><main id="conteudo">${body}</main>${footer(profile,links,lang)}<script src="/shared/redesign.js?v=__BUILD_VERSION__" defer></script><script type="module" src="/shared/v6/scene-init.js?v=__BUILD_VERSION__"></script></body></html>`}
export function repoAction(project,lang='pt'){if(project.repository)return `<a class="button" href="${esc(project.repository)}" target="_blank" rel="noopener noreferrer">GitHub ↗</a>`;const names={'little-x':'TSWill03/LittleX','openclaw-little-x':'TSWill03/OpenClaw_LittleX'};const name=names[project.slug];return name?`<span class="button private-repo">${lang==='en'?'Private repository':'Repositório privado'} · ${name}</span>`:''}
export function media(project,eager=false){const s=project.screenshots?.[0];return s?`<img class="project-image" src="${esc(s.src)}" alt="${esc(s.alt)}" width="${s.width||1600}" height="${s.height||900}" ${eager?'fetchpriority="high"':'loading="lazy"'}>`:'<div class="media-missing"><span>Imagem real pendente</span></div>'}
export function latest(project,activity){return activity.projects?.[project.slug]?.items?.[0]||null}
export const siteUrl=SITE
