import { esc,layout,list } from './common.mjs'

function recent(activity,limit=20){return Object.entries(activity.projects||{}).flatMap(([slug,v])=>(v.items||[]).map(x=>({...x,slug,projectName:v.name||slug}))).sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,limit)}
const EN_FOCUS=['Back-end development with Java, APIs and databases','Flutter applications for web, desktop and mobile','Artificial Intelligence applied to tools and automation','Linux, Docker, servers and networking','Production and customization at BlackLight 3D']
const KIND_EN={Atualização:'Update',Funcionalidade:'Feature',Correção:'Fix',Documentação:'Documentation',Release:'Release'}
const looksPortuguese=(value='')=>/[áàâãéêíóôõúç]/i.test(value)||/\b(adicionados|corrigida|correção|atualização|funcionalidade|normalizadas|documentado|documentação|melhorias|publicado)\b/i.test(value)
function activityDate(item,en){if(!en)return item.displayDate||item.date;try{return new Intl.DateTimeFormat('en-US',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(item.date))}catch{return item.date}}
function activitySummary(item,en){if(!en||!looksPortuguese(item.summary))return item.summary;return `${item.projectName} public project update.`}
function activityKind(item,en){return en?(KIND_EN[item.kindLabel]||item.kindLabel||'UPDATE'):(item.kindLabel||'UPDATE')}

export function about(profile,links,lang='pt'){
 const en=lang==='en',path=en?'/en/about/':'/sobre/',focus=en?EN_FOCUS:(profile.currentFocus||[])
 const course=en?'Bachelor of Computer Science':profile.education.course
 const institution=en?'IF Goiano — Morrinhos Campus':profile.education.institution
 const status=en?'In progress':profile.education.status
 const leadership=en?'President of the Computer Science Academic Center':profile.academicLeadership
 const body=`<section class="page-hero"><div class="shell"><p class="eyebrow">${en?'ABOUT':'SOBRE'}</p><h1>${en?'Curiosity becomes a project. <span>A project becomes a system.</span>':'Curiosidade vira projeto. <span>Projeto vira sistema.</span>'}</h1><p class="lead">${en?'I am Wícolly Pedro Alcântara, a Computer Science student at IF Goiano. I use real projects to learn what happens after code leaves the editor.':`Sou ${esc(profile.name)}, estudante de Ciência da Computação no IF Goiano. Uso projetos reais para aprender o que acontece depois que o código sai do editor.`}</p></div></section><section class="section"><div class="shell about-grid"><article class="surface-card"><p class="eyebrow">${en?'CURRENT FOCUS':'FOCO ATUAL'}</p><h2>Software · AI · Infrastructure</h2>${list(focus,'plain-list')}</article><article class="surface-card"><p class="eyebrow">${en?'EDUCATION':'FORMAÇÃO'}</p><h2>${esc(course)}</h2><p>${esc(institution)}<br>${esc(profile.education.period)} · ${esc(status)}</p><p>${esc(leadership)}</p><a class="button" href="/portfolio/curriculo.pdf">${en?'Resume PDF ↗':'Currículo PDF ↗'}</a></article></div></section><section class="section"><div class="shell lab-panel"><div><p class="eyebrow">${en?'HOW I WORK':'COMO EU TRABALHO'}</p><h2>${en?'Build. Measure. Document.':'Construir. Medir. Documentar.'}</h2><p>${en?'Projects expose the details that appear when a system must be used, deployed, updated and recovered.':'Os projetos mostram os detalhes que só aparecem quando um sistema precisa ser usado, publicado, atualizado e recuperado.'}</p></div><div class="terminal-card"><span>idea → prototype</span><span>test → failure → fix</span><span>deploy → observe</span><span>recover → document</span></div></div></section>`
 return layout({profile,links,title:en?`About | ${profile.name}`:`Sobre | ${profile.name}`,description:en?'Background and current focus.':'Trajetória, formação e foco atual.',path,body,lang})
}

export function journal(profile,links,projects,activity,lang='pt',legacy=false){
 const en=lang==='en',path=en?'/en/journal/':legacy?'/novidades/':'/diario/',items=recent(activity,25)
 const buttons=projects.filter(p=>activity.projects?.[p.slug]?.items?.length).map(p=>`<button class="filter" type="button" data-news-filter="${esc(p.slug)}">${esc(p.name)}</button>`).join('')
 const body=`<section class="page-hero"><div class="shell"><p class="eyebrow">${en?'JOURNAL':'DIÁRIO'}</p><h1>${en?'Build notes, <span>not publishing by obligation.</span>':'Notas de construção, <span>não publicação por obrigação.</span>'}</h1><p class="lead">${en?'Public project activity becomes a curated build log; private projects only publish sanitized notes.':'Atividade pública dos projetos vira um build log com curadoria; projetos privados só publicam notas sanitizadas.'}</p></div></section><section class="section"><div class="shell"><div class="journal-pipeline"><span>GitHub</span><i>→</i><span>sync/build</span><i>→</i><span>${en?'curation':'curadoria'}</span><i>→</i><strong>${en?'Journal':'Diário'}</strong></div><div class="filters"><button class="filter active" type="button" data-news-filter="all">${en?'All':'Todos'}</button>${buttons}</div><div class="journal-list">${items.map(x=>`<article data-news-item="${esc(x.slug)}"><time datetime="${esc(x.date)}">${esc(activityDate(x,en))}</time><div><span class="type-badge">${esc(activityKind(x,en))}</span><h2>${esc(x.projectName)}</h2><p>${esc(activitySummary(x,en))}</p>${x.url?`<a class="text-link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">GitHub ↗</a>`:''}</div></article>`).join('')||`<p class="empty-state">${en?'No public updates in the current cache.':'Sem atualizações públicas no cache atual.'}</p>`}</div></div></section>`
 return layout({profile,links,title:en?'Journal | Wícolly':'Diário | Wícolly',description:en?'Public build notes and project activity.':'Notas públicas de construção e atividade de projetos.',path,body,lang})
}

const SERVICE_EN={
 'Sites e páginas':['Websites and pages','Institutional websites, portfolios and static catalogs with editable content, responsive layouts and deployment.'],
 'Sistemas simples e protótipos':['Simple systems and prototypes','MVPs and tools used to validate a workflow before investing in a larger solution.'],
 'APIs e bancos de dados':['APIs and databases','Data modeling, endpoints and integrations for small applications.'],
 'Linux e Docker':['Linux and Docker','Configuration, diagnosis and documentation of services in controlled environments.'],
 'Servidores de jogos':['Game servers','Installation, migration, management panels, backups and operational routines defined in scope.'],
 'Automações':['Automation','Scripts and integrations that remove repetitive work and record results.'],
 'Soluções com IA':['AI solutions','Prototypes using language models, tools and human approval.'],
 'Impressão 3D':['3D printing','Quotes for custom parts and small batches through BlackLight 3D.'],
}
export function services(profile,links,lang='pt'){const en=lang==='en',path=en?'/en/services/':'/servicos/',items=(profile.services||[]).map(s=>en?{name:SERVICE_EN[s.name]?.[0]||s.name,description:SERVICE_EN[s.name]?.[1]||s.description}:s);const body=`<section class="page-hero"><div class="shell"><p class="eyebrow">${en?'SERVICES':'SERVIÇOS'}</p><h1>${en?'Engineering with <span>clear scope.</span>':'Engenharia com <span>escopo claro.</span>'}</h1><p class="lead">${en?'Websites, systems, automation and infrastructure delivered with explicit scope instead of generic promises.':'Sites, sistemas, automações e infraestrutura contratados sem transformar o portfólio em promessa genérica.'}</p></div></section><section class="section"><div class="shell service-grid">${items.map(s=>`<article class="surface-card"><h2>${esc(s.name)}</h2><p>${esc(s.description)}</p></article>`).join('')}</div><div class="shell actions"><a class="button primary" href="${en?'/en/contact/':'/contato/'}">${en?'Discuss a project →':'Conversar sobre um projeto →'}</a></div></section>`;return layout({profile,links,title:en?`Services | ${profile.name}`:`Serviços | ${profile.name}`,description:en?'Websites, systems, automation and infrastructure with defined scope.':'Sites, sistemas, automações e infraestrutura com escopo definido.',path,body,lang})}

export function contact(profile,links,lang='pt'){
 const en=lang==='en',path=en?'/en/contact/':'/contato/',cards=[['Email',links.email,`mailto:${links.email}`],['LinkedIn',en?'Professional profile':'Perfil profissional',links.linkedin],['GitHub','TSWill03',links.github],['WhatsApp',en?'Technology projects':'Projetos de tecnologia','#']]
 const message=en?'Hello! I came from wicolly.com.br and would like to talk about a technology project.':'Olá! Vim pelo wicolly.com.br e quero conversar sobre um projeto.'
 const body=`<section class="page-hero"><div class="shell"><p class="eyebrow">${en?'CONTACT':'CONTATO'}</p><h1>${en?'Want to build something <span>or talk technical?</span>':'Quer construir algo <span>ou trocar uma ideia técnica?</span>'}</h1></div></section><section class="section"><div class="shell contact-grid">${cards.map(([name,label,href],i)=>`<a class="contact-card" href="${esc(href)}"${i===3?` data-contact data-phone="${esc(links.technologyWhatsApp)}" data-message="${esc(message)}"`:href.startsWith('http')?' target="_blank" rel="noopener noreferrer"':''}><div><p class="eyebrow">${name}</p><h2>${esc(label)}</h2></div><small>${en?'Open →':'Abrir →'}</small></a>`).join('')}</div></section>`
 return layout({profile,links,title:en?'Contact | Wícolly':'Contato | Wícolly',description:en?'Professional contact channels.':'Canais de contato profissional.',path,body,lang})
}

export function privacy(profile,links,lang='pt'){
 const en=lang==='en',path=en?'/en/privacy/':'/privacidade/'
 const body=`<section class="page-hero"><div class="shell"><p class="eyebrow">${en?'PRIVACY':'PRIVACIDADE'}</p><h1>${en?'A public presence with <span>minimal data collection.</span>':'Uma presença pública com <span>o mínimo de coleta necessária.</span>'}</h1><p class="lead">${en?'The site is mostly static. Quote forms prepare messages in the browser and open external communication channels.':'O site é majoritariamente estático. Formulários de orçamento preparam mensagens no navegador e abrem canais externos.'}</p></div></section><section class="section"><div class="shell prose"><h2>${en?'Contact':'Contato'}</h2><p>${en?'When you open WhatsApp, email, GitHub or LinkedIn, the external platform’s privacy policy applies.':'Ao abrir WhatsApp, e-mail, GitHub ou LinkedIn, a política da plataforma externa passa a valer.'}</p><h2>${en?'Technical data':'Dados técnicos'}</h2><p>${en?'We do not publish credentials, internal addresses, keys or sensitive operational topology.':'Não publicamos credenciais, endereços internos, chaves ou topologia operacional sensível.'}</p></div></section>`
 return layout({profile,links,title:en?`Privacy | ${profile.name}`:`Privacidade | ${profile.name}`,description:en?'Privacy and external services used by wicolly.com.br.':'Privacidade e serviços externos no wicolly.com.br.',path,body,lang})
}

export function resume(profile,links,projects){const selected=projects.filter(p=>['campus-flow','veredra','little-x','blacklight-3d'].includes(p.slug));return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Currículo | ${esc(profile.name)}</title><link rel="stylesheet" href="/shared/redesign.css?v=__BUILD_VERSION__"><link rel="stylesheet" href="/shared/v6/core.css?v=__BUILD_VERSION__"></head><body class="resume"><main><header><p class="eyebrow">CURRÍCULO</p><h1>${esc(profile.name)}</h1><p>${esc(profile.headline)}</p><p>${esc(profile.location)} · <a href="mailto:${esc(links.email)}">${esc(links.email)}</a> · <a href="${esc(links.linkedin)}">LinkedIn</a> · <a href="${esc(links.github)}">GitHub</a></p></header><section><h2>Perfil</h2><p>${esc(profile.shortBio)}</p></section><section><h2>Formação</h2><h3>${esc(profile.education.course)}</h3><p>${esc(profile.education.institution)} · ${esc(profile.education.period)} · ${esc(profile.education.status)}</p></section><section><h2>Projetos selecionados</h2>${selected.map(p=>`<article><h3>${esc(p.name)} <small>— ${esc(p.status)}</small></h3><p>${esc(p.shortDescription)}</p></article>`).join('')}</section></main></body></html>`}
