import fs from 'node:fs/promises'
import path from 'node:path'
import { home,projectsIndex,projectCase,aiLab } from './main-pages.mjs'
import { about,journal,services,contact,privacy,resume } from './content-pages.mjs'
import { infrastructurePage,infraDetail } from './infra-pages.mjs'
import { blacklightHome,blacklightProjects,blacklightQuote } from './blacklight-pages.mjs'
async function write(dist,dir,html){const target=path.join(dist,dir,'index.html');await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,`${html}\n`)}
function englishBlacklightHome(profile,links){return blacklightHome(profile,links,'en').replaceAll('#funcionais','#functional').replaceAll('#personalizados','#custom').replaceAll('#prototipos','#prototype')}
export async function renderSite({root,distDir}){const read=async r=>JSON.parse(await fs.readFile(path.join(root,r),'utf8'));const [profile,links,projects,activity,products,infra]=await Promise.all([read('data/profile.json'),read('data/social-links.json'),read('data/projects.json'),read('data/generated/github-activity.json'),read('data/blacklight-products.json'),read('data/infrastructure.json')]);
 await fs.writeFile(path.join(distDir,'index.html'),`${home(profile,links,projects,activity,'pt')}\n`)
 await write(distDir,'sobre',about(profile,links,'pt'));await write(distDir,'projetos',projectsIndex(profile,links,projects,activity,'pt'));for(const p of projects)await write(distDir,path.join('projetos',p.slug),projectCase(profile,links,p,activity,'pt'));await write(distDir,'ia',aiLab(profile,links,'pt'));await write(distDir,'diario',journal(profile,links,projects,activity,'pt'));await write(distDir,'novidades',journal(profile,links,projects,activity,'pt',true));await write(distDir,'servicos',services(profile,links));await write(distDir,'infraestrutura',infrastructurePage(profile,links,infra,'pt'));await write(distDir,'borda',infraDetail(profile,links,null,'edge'));for(const s of infra.servers)await write(distDir,s.slug,infraDetail(profile,links,{...s,publicRoute:s.publicRoute||`/${s.slug}/`}));await write(distDir,'contato',contact(profile,links,'pt'));await write(distDir,'privacidade',privacy(profile,links));await write(distDir,'blacklight3d',blacklightHome(profile,links,'pt'));await write(distDir,path.join('blacklight3d','projetos'),blacklightProjects(profile,links,'pt'));await write(distDir,path.join('blacklight3d','orcamento'),blacklightQuote(profile,links,products,'pt'));await write(distDir,'portfolio',projectsIndex(profile,links,projects,activity,'pt','/portfolio/'));await fs.writeFile(path.join(distDir,'portfolio','curriculo.html'),`${resume(profile,links,projects)}\n`)
 await write(distDir,'en',home(profile,links,projects,activity,'en'));await write(distDir,path.join('en','about'),about(profile,links,'en'));await write(distDir,path.join('en','projects'),projectsIndex(profile,links,projects,activity,'en'));for(const p of projects)await write(distDir,path.join('en','projects',p.slug),projectCase(profile,links,p,activity,'en'));await write(distDir,path.join('en','ai'),aiLab(profile,links,'en'));await write(distDir,path.join('en','infrastructure'),infrastructurePage(profile,links,infra,'en'));await write(distDir,path.join('en','journal'),journal(profile,links,projects,activity,'en'));await write(distDir,path.join('en','contact'),contact(profile,links,'en'));await write(distDir,path.join('en','blacklight3d'),englishBlacklightHome(profile,links));await write(distDir,path.join('en','blacklight3d','projects'),blacklightProjects(profile,links,'en'));await write(distDir,path.join('en','blacklight3d','quote'),blacklightQuote(profile,links,products,'en'))
}
