Alias /blacklight3d /var/www/html

<Directory /var/www/html>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<IfModule mod_headers.c>
    Header always set X-BlackLight-Subpath "blacklight3d"
</IfModule>
